### ISSUE TITLE
Linked_list

### ISSUE THREAD

**Issue by jaewook718** [Maker-H/GroupStudy_Algo_Log#11]
![LLdrawio](https://user-images.githubusercontent.com/102957590/216055414-52c20fcd-a09e-4b3f-bb40-4ac5d09069b9.png)

**Comment by Maker-H** [comment]
> ![LLdrawio](https://user-images.githubusercontent.com/102957590/216055414-52c20fcd-a09e-4b3f-bb40-4ac5d09069b9.png)
> 

등록은 안하셔도 됨 ^^
